-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `full-stack-ecommerce`;

CREATE SCHEMA `full-stack-ecommerce`;
USE `full-stack-ecommerce` ;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`

-- `unit_price` DECIMAL(13,2) DEFAULT NULL,
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` INT(11) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------

INSERT INTO product_category(category_name) VALUES ('Stud Earring');
INSERT INTO product_category(category_name) VALUES ('Fashion Earring');
INSERT INTO product_category(category_name) VALUES ('Drop Earring');
INSERT INTO product_category(category_name) VALUES ('Pearl Earring');

-- -----------------------------------------------------
-- Stud Earring
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1000', 'Zircon flower earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1000.png', 1, 100, 114, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1001', 'Square Zircon Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1001.png', 1, 100, 120, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1002', 'Pink butterfly cats eye stone earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1002.png', 1, 100, 114, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1003', 'Blue Butterfly Cats Eye earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1003.png', 1, 100, 113, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1004', 'Gradient Blue Butterfly Pearl earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1004.png', 1, 100, 118, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1005', 'Icy colorful flower stud earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1005.png', 1, 100, 123, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1006', 'French super fairy pearl flower earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1006.png', 1, 100, 114, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1007', 'Mori green crystal butterfly earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1007.png', 1, 100, 116, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1008', 'Small fresh butterfly pearl earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1008.png', 1, 100, 125, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1009', 'Colorful mermaid tail Zircon earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1009.png', 1, 100, 123, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1010', 'Butterfly pearl fishtail small tassel earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1010.png', 1, 100, 124, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1011', 'Micro-inlaid zircon light luxury exquisite drop earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1011.png', 1, 100, 119, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1012', 'French irish flower earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1012.png', 1, 100, 124, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1013', 'Fashion mori gradient spell blue crystal leaf earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1013.png', 1, 100, 119, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1014', 'White Acrylic Flower Stud Folded Florals Korean Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1014.png', 1, 100, 122, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1015', 'Enamel Round Pendant Drop Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1015.png', 1, 100, 122, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1016', 'Sweet Temperament Camellia Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1016.png', 1, 100, 127, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1017', 'Boho Ethnic Water Crystal Drop Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1017.png', 1, 100, 113, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1018', 'Spring Flower Freshwater Pearl Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1018.png', 1, 100, 126, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1019', 'Red Velvet Rose Flower Retro Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1019.png', 1, 100, 113, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1020', 'White Flower Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1020.png', 1, 100, 119, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1021', 'French Romantic Camellia Pearl Pendant Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1021.png', 1, 100, 118, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1022', 'White Enamel Oil Flower Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1022.png', 1, 100, 126, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1023', 'Korean New Cute Daisy Flower Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1023.png', 1, 100, 122, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('STUD-EARRING-1024', 'Sweet Flower Shaped Drop Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/studs/stud-onlineshop-1024.png', 1, 100, 116, 1, NOW());

-- -----------------------------------------------------
-- Fashion Earring
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1000', 'Zircon flower earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1000.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1001', 'Square Zircon Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1001.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1002', 'Pink butterfly cats eye stone earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1002.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1003', 'Blue Butterfly Cats Eye earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1003.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1004', 'Gradient Blue Butterfly Pearl earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1004.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1005', 'Icy colorful flower stud earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1005.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1006', 'French super fairy pearl flower earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1006.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1007', 'Mori green crystal butterfly earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1007.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1008', 'Small fresh butterfly pearl earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1008.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1009', 'Colorful mermaid tail Zircon earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1009.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1010', 'Butterfly pearl fishtail small tassel earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1010.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1011', 'Micro-inlaid zircon light luxury exquisite drop earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1011.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1012', 'French irish flower earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1012.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1013', 'Fashion mori gradient spell blue crystal leaf earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1013.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1014', 'White Acrylic Flower Stud Folded Florals Korean Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1014.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1015', 'Enamel Round Pendant Drop Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1015.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1016', 'Sweet Temperament Camellia Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1016.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1017', 'Boho Ethnic Water Crystal Drop Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1017.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1018', 'Spring Flower Freshwater Pearl Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1018.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1019', 'Red Velvet Rose Flower Retro Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1019.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1020', 'White Flower Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1020.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1021', 'French Romantic Camellia Pearl Pendant Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1021.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1022', 'White Enamel Oil Flower Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1022.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1023', 'Korean New Cute Daisy Flower Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1023.png', 1, 100, 118, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FASHION-EARRING-1024', 'Sweet Flower Shaped Drop Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/fashions/fashion-onlineshop-1024.png', 1, 100, 118, 2, NOW());

-- -----------------------------------------------------
-- Drop Earring
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1000', 'Fashion Elegant Luxurious Four Leaf Clover Opal Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1000.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1001', 'Fashion Exquisite Pearl Geometric Shape Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1001.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1002', 'Fashion Exquisite Pearl Geometric Shape Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1002.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1003', 'Large Zircon Shiny Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1003.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1004', 'Retro Mysterious Black Zircon Hoop Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1004.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1005', 'Retro Mysterious Black Zircon Hoop Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1005.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1006', 'Minimalist Womens Earrings Crafted from Quality', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1006.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1007', 'Korean White Imitation Pearl Zircon Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1007.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1008', 'Black velvet pearl earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1008.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1009', 'Silver needle unique camellia stud earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1009.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1010', 'French Vintage Imitation Pearl Clip on Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1010.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1011', 'Sweet Bohemian Leaf Dangle Tassel Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1011.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1012', 'Inspired Silver Inlaid Gemstone Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1012.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1013', 'Beautiful Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1013.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1014', 'Camellia Flower Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1014.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1015', 'Luxury Crystal Green Zircon Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1015.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1016', 'Bow Knot Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1016.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1017', 'Inlaid Zircon Round Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1017.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1018', 'Love Shape Small Stud Beautiful Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1018.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1019', 'Enamel Charm Alloy Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1019.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1020', 'French Vintage Imitation Pearl Clip on Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1020.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1021', 'Korean New Simple Temperament Circle Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1021.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1022', 'Black Camellia Imitation Pearl Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1022.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1023', 'Trendy Style Camellia Flower Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1023.png', 1, 100, 117, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DROP-EARRING-1024', 'Fashion Creativity Design Pearl Earring', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/drops/drop-onlineshop-1024.png', 1, 100, 117, 3, NOW());

-- -----------------------------------------------------
-- Pearl Earring
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1000', 'Fashion Elegant Luxurious Four Leaf Clover Opal Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1000.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1001', 'Fashion Exquisite Pearl Geometric Shape Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1001.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1002', 'Fashion Exquisite Pearl Geometric Shape Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1002.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1003', 'Large Zircon Shiny Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1003.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1004', 'Retro Mysterious Black Zircon Hoop Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1004.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1005', 'Retro Mysterious Black Zircon Hoop Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1005.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1006', 'Minimalist Womens Earrings Crafted from Quality', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1006.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1007', 'Korean White Imitation Pearl Zircon Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1007.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1008', 'Black velvet pearl earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1008.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1009', 'Silver needle unique camellia stud earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1009.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1010', 'French Vintage Imitation Pearl Clip on Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1010.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1011', 'Sweet Bohemian Leaf Dangle Tassel Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1011.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1012', 'Inspired Silver Inlaid Gemstone Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1012.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1013', 'Beautiful Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1013.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1014', 'Camellia Flower Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1014.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1015', 'Luxury Crystal Green Zircon Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1015.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1016', 'Bow Knot Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1016.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1017', 'Inlaid Zircon Round Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1017.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1018', 'Love Shape Small Stud Beautiful Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1018.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1019', 'Enamel Charm Alloy Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1019.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1020', 'French Vintage Imitation Pearl Clip on Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1020.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1021', 'Korean New Simple Temperament Circle Pearl Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1021.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1022', 'Black Camellia Imitation Pearl Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1022.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1023', 'Trendy Style Camellia Flower Stud Earrings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1023.png', 1, 100, 116, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PEARL-EARRING-1024', 'Fashion Creativity Design Pearl Earring', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/products/pearls/pearl-onlineshop-1024.png', 1, 100, 116, 4, NOW());

